name: geo-rnaseq-mining
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - python=3.12
  - snakemake-minimal=8
  - snakemake-executor-plugin-slurm
  - pyyaml
  - jsonschema
  - numpy
  - pandas
  - patsy
  - scipy
