snakefile: workflow/Snakefile
configfile: config/config.yaml
executor: slurm
jobs: 50
use-conda: true
rerun-incomplete: true
printshellcmds: true
show-failed-logs: true
latency-wait: 60
default-resources:
  - mem_mb=2000
  - runtime_min=30
  - disk_mb=2000
slurm-logdir: logs/slurm
